{% set version = "1.0.7" %}


package:
  name: fs.smbfs
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/f/fs.smbfs/fs.smbfs-{{ version }}.tar.gz
  sha256: 862bca01a769bfa3c14fc2788d7492c13d529d0c717c37abe1568440a290707a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - fs >=2.4
    - pysmb >=1.1.22,!=1.1.26,!=1.1.29,<=1.2.9.1
    - six >=1.10.0,<2

test:
  imports:
    - fs.smbfs
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/althonos/fs.smbfs
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Pyfilesystem2 over SMB using pysmb
  description: >
    Once created, the SMBFS filesystem behaves like any other filesystem see the Pyfilesystem2 documentation https://pyfilesystem2.readthedocs.io.

extra:
  recipe-maintainers:
    - althonos
    - timkpaine
